version: '3.8'

services:
  # Scheduler service - runs continuously and updates data daily
  scheduler:
    build: .
    container_name: data-scheduler
    command: python services/scheduler_daemon.py
    restart: unless-stopped
    volumes:
      - ./data/cache:/app/data/cache           # Persist cached data
      - ./config:/app/config                   # Config files (read/write)
      - ./logs:/app/logs                       # Log files
      - ./performance:/app/performance         # Performance metrics
    environment:
      - TZ=${TZ:-UTC}
      - UPDATE_HOUR=${UPDATE_HOUR:-1}          # Default 1 AM UTC
      - UPDATE_MINUTE=${UPDATE_MINUTE:-0}
    depends_on: []
    networks:
      - backtester-network

  # Backtest service - removed (develop separately)
  # Run backtests directly: python main.py
  # Uses same cache from data/cache/ directory

  # Bulk fetch service - run once for initial data collection (uses multi-exchange discovery)
  bulk-fetch:
    build: .
    container_name: bulk-fetcher
    command: python scripts/bulk_fetch_data.py
    volumes:
      - ./data/cache:/app/data/cache
      - ./config:/app/config
      - ./logs:/app/logs
      - ./performance:/app/performance
    profiles:
      - tools  # Don't start automatically
    networks:
      - backtester-network

networks:
  backtester-network:
    driver: bridge

