# Crypto Backtesting Configuration

# Exchange Settings
exchange:
  name: coinbase  # Options: binance, coinbase, kraken, etc.
  # Optional: filter which symbols/timeframes to test
  # If omitted or set to null, uses ALL from exchange_metadata.yaml
  symbols: null  # or list like [BTC/USD, ETH/USD] to filter
  timeframes: null  # or list like [1h, 1d] to filter

# Backtest Date Range
backtest:
  start_date: "2017-01-01"  # Format: YYYY-MM-DD
  end_date: "2025-10-27"
  initial_capital: 100000.0  # Starting capital in quote currency
  verbose: false  # Minimal output for multi-run tests
  
# Quick test configuration (overrides above when --quick flag is used)
quick_test:
  symbols: [BTC/USD]  # Single symbol for quick testing
  timeframes: [1h]     # Single timeframe for quick testing
  verbose: true  # Detailed output for quick tests

# Trading Settings
trading:
  use_exchange_fees: false  # Set to false to use hardcoded fees below
  fee_type: taker  # "maker" or "taker" - Coinbase Advanced Trade rates
  slippage: 0.0005  # 0.05% slippage
  risk_per_trade: 0.01  # Risk 1% of capital per trade (default stop loss distance)
  position_size: 0.1  # Maximum position size relative to portfolio (0.1 = 10%)
  
  # Coinbase Advanced Trade fees (hardcoded for accuracy)
  commission: 0.006  # 0.6% (taker fee - default)
  commission_maker: 0.004  # 0.4% (maker fee - not used unless fee_type is 'maker')

# Strategy Parameters (will vary by strategy)
strategy:
  name: sma_cross
  parameters:
    fast_period: 20
    slow_period: 50
    
# Data Settings
data:
  cache_enabled: true
  cache_directory: data/cache
  historical_start_date: "2017-01-01"  # Default start date for data collection (configurable)

# Parallel Execution Settings
parallel:
  # Execution mode
  mode: auto  # Options: auto, manual
  
  # Manual override (only used if mode=manual)
  max_workers: null  # null = auto-detect, or specify 1-N
  
  # Auto-tuning parameters
  memory_safety_factor: 0.75  # Use max 75% of available RAM
  cpu_reserve_cores: 1        # Reserve N cores for system

