last_updated: '2025-10-28T20:50:00.000000'
# Exchange to use for actual trading/execution
exchange: coinbase
# List of exchanges to search for historical data (in priority order)
# The system will test each exchange and select the one with the most historical data
exchanges:
- coinbase
- binance
- kraken
- bybit
- okx
timeframes:
- 1m
- 5m
- 15m
- 30m
- 1h
- 2h
- 6h
- 1d
top_markets:
- BTC/USD
- ETH/USD
- BNB/USD
- XRP/USD
- SOL/USD
- ADA/USD
- DOGE/USD
- AVAX/USD
- DOT/USD
- SHIB/USD
- LTC/USD
- UNI/USD
- LINK/USD
- ATOM/USD
- XLM/USD
- BCH/USD
- ALGO/USD
- VET/USD
- FIL/USD
- ICP/USD
- ETC/USD
- HBAR/USD
- XTZ/USD
- APT/USD
- EGLD/USD
- LDO/USD
- ARB/USD
- AAVE/USD
- MKR/USD
- GRT/USD
- QNT/USD
- NEAR/USD
- STX/USD
- COMP/USD
- INJ/USD
- SNX/USD
- CAKE/USD
- KSM/USD
- CRV/USD
- RPL/USD
- IMX/USD
- OP/USD
- SUI/USD
- BONK/USD
- SAND/USD
- AXS/USD
- MANA/USD
- CHZ/USD
- FET/USD
- FLOW/USD
- ZEC/USD
- DASH/USD
- YFI/USD
- 1INCH/USD
- BAT/USD
- ZRX/USD
- LRC/USD
- BNT/USD
- KNC/USD
- BAL/USD
- CVC/USD
- STORJ/USD
- PAXG/USD
- RSR/USD
- OCEAN/USD
- BAND/USD
- ANKR/USD
- AUDIO/USD
- GLM/USD
- HNT/USD
- ZEN/USD
fees:
  maker: 0.004
  taker: 0.006
