name: Cache Compatibility Tests

on:
  pull_request:
    paths:
      - 'data/cache_manager.py'
      - 'data/validator.py'
      - 'data/updater.py'
      - 'data/fetcher.py'
  push:
    branches: [main]
    paths:
      - 'data/cache_manager.py'
      - 'data/validator.py'
      - 'data/updater.py'
      - 'data/fetcher.py'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    
    - name: Run compatibility tests
      run: |
        pytest tests/test_cache_compatibility.py -v

