name: Build, Test, and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]  # Matches pyproject.toml requires-python (>=3.11) and Dockerfile (python:3.11-slim)
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          pip install -e ".[dev]"
      
      - name: Run unit tests
        run: pytest tests/unit/ -v --tb=short
      
      - name: Run integration tests
        run: pytest tests/integration/ -v --tb=short
      
      - name: Run system tests
        run: pytest tests/system/ -v --tb=short
      
      - name: Run E2E tests (if data available)
        run: pytest tests/e2e/ -v -m "not requires_data" --tb=short || true

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install -e ".[dev]"
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./deployment/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/backtester-mvp:latest
            ghcr.io/${{ github.repository_owner }}/backtester-mvp:${{ github.sha }}

  deploy:
    runs-on: self-hosted
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Pull latest image
        shell: powershell
        run: docker pull ghcr.io/${{ github.repository_owner }}/backtester-mvp:latest
      
      - name: Deploy with docker-compose
        shell: powershell
        run: |
          cd C:\backtester\deployment
          docker-compose pull
          
          # Check if data exists - if not, run bulk fetch in background
          $CSV_COUNT = (Get-ChildItem -Path ..\data\*.csv -ErrorAction SilentlyContinue | Measure-Object).Count
          if ($CSV_COUNT -eq 0) {
            Write-Host "No cache files found - starting bulk fetch in background..."
            Start-Process powershell -ArgumentList "-Command", "cd C:\backtester\deployment; docker-compose run --rm bulk-fetch > ..\artifacts\logs\bulk_fetch_deploy.log 2>&1" -WindowStyle Hidden
            Write-Host "Bulk fetch started in background"
          } else {
            Write-Host "Found $CSV_COUNT cache files - skipping bulk fetch"
          }
          
          docker-compose up -d --no-deps scheduler
          docker-compose ps
