name: Tests

on:
  push:
    branches-ignore: [main]  # Skip main - deploy.yml handles testing on main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -e ".[dev]"
      - name: Run unit tests
        run: pytest tests/unit/ -v --tb=short
      - name: Run integration tests
        run: pytest tests/integration/ -v --tb=short
      - name: Run system tests
        run: pytest tests/system/ -v --tb=short
      - name: Run E2E tests (if data available)
        run: pytest tests/e2e/ -v -m "not requires_data" --tb=short || true

